FROM ubuntu:xenial

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
RUN apt-get update && apt-get install -y python3.6 python3.6-dev python3-pip git gfortran gcc build-essential pkg-config libfreetype6 libxft-dev
RUN cp /etc/apt/sources.list /etc/apt/sources.list~
RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
RUN apt-get update
RUN dpkg --configure -a



RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2

RUN python3 -m pip install --upgrade pip

#RUN python3 -m pip install pymarket
RUN git clone https://github.com/gus0k/pymarket.git
WORKDIR /pymarket
RUN python3 -m pip install -r requirements.txt
RUN python3 setup.py install



