FROM ubuntu:bionic

RUN apt update && apt install --yes python3-pip=9.0.1-2.3~ubuntu1.18.04.1 git


RUN python3 -m pip install pymarket
RUN python3 -m pip install pytest

WORKDIR /home

RUN git clone https://github.com/gus0k/pymarket

WORKDIR /home/pymarket
RUN pytest 



