FROM ubuntu:xenial

RUN apt-get update && apt-get install -y python3 python3-pip git software-properties-common


RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
RUN apt-get -y install python3.6
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2

RUN python3 -m pip install pymarket pytest

WORKDIR /home
RUN git clone https://github.com/gus0k/pymarket
WORKDIR /home/pymarket

RUN pytest


