# -*- mode: ruby -*- 
# vi: set ft=ruby : 
#
# INSTRUCTIONS
# Assumptions:
#   - A working installation, and knowledge, of Vagrant
#   - A DigitalOcean account: https://m.do.co/c/9a152ce8c79e
#   - Vagrant plugins installed:
#     - vagrant-digitalocean
#     - vagrant-omnibus 
#   - Shell environment variables:
#     - DIGITALOCEAN_TOKEN
#     - DIGITALOCEAN_SSH_KEY_NAME

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :digital_ocean do |provider, override| 
    provider.token  = ENV['DIGITALOCEAN_TOKEN']

    provider.image  = 'ubuntu-16-04-x64' # vagrant digitalocean-list images $DIGITALOCEAN_TOKEN
    provider.region = 'nyc3'             # vagrant digitalocean-list regions $DIGITALOCEAN_TOKEN
    provider.size   = 's-2vcpu-4gb'      # vagrant digitalocean-list sizes $DIGITALOCEAN_TOKEN

    provider.ssh_key_name = ENV['DIGITALOCEAN_SSH_KEY_NAME'] 
    override.ssh.private_key_path = '~/.ssh/id_rsa' 
    override.vm.box     = 'digital_ocean'
    override.vm.box_url = 'https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box'

    provider.ca_path = "/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt" 
  end 

  config.vm.provision 'chef_zero' do |chef|
    # Specify the local paths where Chef data is stored
    chef.cookbooks_path = ['site-cookbooks', 'vendor/zero/cookbooks']
    chef.nodes_path     = 'vendor/zero/nodes'
    # Add attributes
    chef.json = {
      user: {
        username: 'pymarket'
      },
      apt: {
        packages: {
          'apt-transport-https': {action: 'install'},
          'ca-certificates': {action: 'install'},
          'curl': {action: 'install'},
          'software-properties-common': {action: 'install'}
        }
      }
    }
  end
end
